"""initial migration

Revision ID: 9ebac3b63fa9
Revises: 
Create Date: 2026-05-24 19:24:44.540871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ebac3b63fa9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compound_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compound_aliases_name'))

    op.drop_table('compound_aliases')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compound_aliases',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('compound_id', sa.INTEGER(), nullable=True),
    sa.Column('smiles', sa.TEXT(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=64), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compound_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compound_aliases_name'), ['name'], unique=False)

    # ### end Alembic commands ###
